version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: details about product
        columns:
          - name: products_id
            description: id del producto
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description:  precio del producto
      - name: sales
        identifier: raw_gz_sales
        description: details about sales
        # Freshness testing - make sure to fill in the ...
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}  
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: fecha de la compra
          - name: orders_id
            description:  id de la orden 
          - name: pdt_id
            description:  id del producto
          - name: revenue
            description:  ganacia de la venta
          - name: quantity
            description:  cantidad de producto
      - name: ship
        identifier: raw_gz_ship
        description: details about ship
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null 
          - name: shipping_free
            description: ship the fee
          - name: log_cost
            description: log the ship 
          - name: ship_cost
            description: cost the ship  